name: Build HMAPlusPlus

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ARM GNU Toolchain and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-aarch64-linux-gnu

    - name: Patch Makefile to use correct toolchain
      run: |
        sed -i 's|/home/lshwjgpt/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-gcc|aarch64-linux-gnu-gcc|g' Makefile
        sed -i 's|/home/lshwjgpt/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-g++|aarch64-linux-gnu-g++|g' Makefile
        sed -i 's|/home/lshwjgpt/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-objcopy|aarch64-linux-gnu-objcopy|g' Makefile

    - name: Build with Make
      run: make

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: hmaplusplus-binary
        path: |
          HMA++.kpm
